### PR TITLE
Add integration test for zip stuff and gcc

### LINKED ISSUE #123: Make the basic_zip integration test also test gcc

### PR DESCRIPTION
**Pull request by calixteman**
Fix #123.

### CODE REVIEW

**Comment by marco-c** [comment]
This will fail on Mac as we can't run GCC tests there. You can wait for #125 and rebase on top of it, or disable the gcc case on Mac.

**Comment by marco-c** [comment]
There are some test failures with GCC 4.9.
#125 was merged in the meantime, so you can remove the mac if.

**Comment by marco-c** [comment]
Here's where the failure is happening: https://travis-ci.org/marco-c/grcov/jobs/384801285#L1053.

**Comment by marco-c** [comment]
There's some problem in the rebasing, I see `This branch cannot be rebased due to conflicts`.

**Comment by calixteman** [comment]
Strange

**Pull request closed without merging**
